id: 'republishAudiQ7Away'                                                     
alias: 'L: Audi Q7 Away to MQTT'                                                 
trigger:                                                                      
  platform: state                                                             
  entity_id: device_tracker.audi_q7_ibeacon_tracker
  to: 'not_home'                                                              
action:                                                                       
  - service: mqtt.publish                                                     
    data_template:                                                            
      topic: 'location/car/audi_q7_gps'                                       
      retain: false                                                           
      payload:                                                                
              '                                                               
                  {"battery_level":100,                                       
                  "longitude":0.0,                                            
                  "latitude":0.0,                                             
                  "gps_accuracy":100,                                         
                  "tst": {{ as_timestamp(now()) | int }},                     
                  "_type":"location",                                         
                  "tid":"sc"}                                                 
              '                                                               
