- id: 'republishAudiA6Away'
  alias: 'Audi A6 Away to MQTT'      
  initial_state: 'on'                        
  trigger:                                            
    platform: state  
    entity_id: device_tracker.audi_a6_bt
    to: 'not_home'                                                       
  action:                                                                                                                            
    - service: mqtt.publish                                                                        
      data_template:                                                          
        topic: 'location/car/audi_a6_gps'   
        retain: false                                      
        payload:                       
                '                                                                   
                    {"battery_level":100,     
                    "longitude":0.0,         
                    "latitude":0.0,
                    "gps_accuracy":100,
                    "tst": {{ as_timestamp(now()) | int }},                                              
                    "_type":"location",                                                         
                    "tid":"sc"}                                                               
                '                                                                                     
                                                                                                                                     
- id: 'republishAudiA6Home'                                                                        
  alias: 'Audi A6 Home to MQTT'                        
  initial_state: 'on' 
  trigger:                               
    platform: state   
    entity_id: device_tracker.audi_a6_bt                    
    to: 'home'        
  action:                  
    - service: mqtt.publish          
      data_template:                         
        topic: 'location/car/audi_a6_gps'             
        retain: false
        payload:                             
                '                                                        
                    {"battery_level":100,                                      
                    "longitude":{{ states.zone.tworoads.attributes.longitude }},
                    "latitude":{{ states.zone.tworoads.attributes.latitude }},
                    "gps_accuracy":100,     
                    "tst": {{ as_timestamp(now()) | int }},
                    "_type":"location",
                    "tid":"sc"}
                '                             

- id: 'republishAudiQ7Away'
  alias: 'Audi Q7 Away to MQTT'
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.audi_q7_bt
    to: 'not_home'
  action:
    - service: mqtt.publish
      data_template:
        topic: 'location/car/audi_q7_gps'
        retain: false
        payload:
                '
                    {"battery_level":100,
                    "longitude":0.0,
                    "latitude":0.0,
                    "gps_accuracy":100,
                    "tst": {{ as_timestamp(now()) | int }},
                    "_type":"location",
                    "tid":"sc"}
                '

- id: 'republishAudiQ7Home'
  alias: 'Audi Q7 Home to MQTT'
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: device_tracker.audi_q7_bt
    to: 'home'
  action:
    - service: mqtt.publish
      data_template:
        topic: 'location/car/audi_q7_gps'
        retain: false
        payload:
                '
                    {"battery_level":100,
                    "longitude":{{ states.zone.tworoads.attributes.longitude }},
                    "latitude":{{ states.zone.tworoads.attributes.latitude }},
                    "gps_accuracy":100,
                    "tst": {{ as_timestamp(now()) | int }},
                    "_type":"location",
                    "tid":"sc"}
                '

