homeassistant:
  # Name of the location where Home Assistant is running
  name: Tworoads
  # Location required to calculate the time the sun rises and sets
  latitude: !secret tworoads_latitude
  longitude: !secret tworoads_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  # 295 ft/ 90m
  elevation: 90
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Currency:
  currency: USD
  # URLS:
#  internal_url: "https://homeassistant.local:8123"
  internal_url: "https://homeassistant.local:8123"
  external_url: "https://hass.tworoads.net:8123"
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  allowlist_external_dirs:                                                                      
    - /config                                                                                   

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Mobile App
mobile_app:

# Discover some devices automatically
discovery:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
  ssl_certificate:  !secret ssl_certificate
  ssl_key:          !secret ssl_key

telegram_bot:
  - platform: polling # polling or broadcast
    api_key: !secret telegram_apikey
    parse_mode: html # otherwise '_' are interpreted as for italics in msg parser
    allowed_chat_ids:
      - !secret telegram_chatid # First chat Group "HA Tworoads"
      - !secret telegram_userid # "Scott"

notify:
  - name: telegram_tworoads
    platform: telegram
    api_key: !secret telegram_apikey
    chat_id: !secret telegram_chatid

camera:
  - platform: local_file
    name: Front Door Snapshot
    file_path: /config/www/snapshots/tr_front_door.png
  - platform: local_file
    name: Side Yard Snapshot
    file_path: /config/www/snapshots/tr_side_yard.png

device_tracker:
  - platform: mqtt_json
    devices:
      audi_a6_gps: 'location/car/audi_a6_gps'
      audi_q7_gps: 'location/car/audi_q7_gps'
      toyota_rav4_gps: 'location/car/toyota_rav4_gps'

logger:
  default: info
  logs:
#   homeassistant.components.automation: debug
#    homeassistant.components.command_line.switch: warning
    homeassistant.components.device_tracker.unifi: info
#   homeassistant.components.media_player: warning
#   homeassistant.components.unifi: debug

# Sensors
sensor:
  - platform: gpsd
    name: Tworoads GPS
    host: 192.168.37.157
    scan_interval: 60
  - platform: mqtt                                                
    name: "Room Assistant Basement"
    state_topic: room-assistant/status/basement
  - platform: mqtt                                                
    name: "Room Assistant Den"
    state_topic: room-assistant/status/den
  - platform: mqtt
    name: "Room Assistant Garage"
    state_topic: room-assistant/status/garage
  - platform: mqtt
    state_topic: 'environment/tworoads_garage/bme280_temperature'
    name: 'Garage Temperature'
    unit_of_measurement: '°F'
  - platform: mqtt
    state_topic: 'environment/tworoads_garage/bme280_humidity'
    name: 'Garage Humidity'    
  - platform: mqtt
    state_topic: 'environment/tworoads_garage/bme280_pressure'
    unit_of_measurement: 'hPa'
    name: 'Garage Pressure'
  - platform: mqtt
    state_topic: 'environment/tworoads_garage/bme280_sealevel_pressure'
    unit_of_measurement: 'hPa'
    name: 'Garage Sealevel Pressure'
  # Weewx Weather
  - platform: rest
    resource: http://192.168.37.157/weewx/daily.json
    name: Weewx Weather
    scan_interval: 150
    force_update: true
    json_attributes:
      - time
      - current
      - almanac
    value_template: '{{ value_json.location }}'
  - platform: rest
    name: "House Energy Delivered"
    resource: "http://192.168.37.155:3480/data_request?id=variableget&DeviceNum=105%serviceId=urn:micasaverde-com:serviceId:EnergyMetering1&Variable=states"
    method: "GET"
    scan_interval: 60
    unit_of_measurement: kWh
    value_template: '{{ value_json[21].value }}'
  - platform: rest
    name: "House Power Demand"
    resource: "http://192.168.37.155:3480/data_request?id=variableget&DeviceNum=105%serviceId=urn:micasaverde-com:serviceId:EnergyMetering1&Variable=states"
    method: "GET"
    scan_interval: 60
    unit_of_measurement: kW
    value_template: '{{ (value_json[23].value | float) / 1000 | round(2) }}'
  - platform: rest
    name: "Vera House Mode"
    resource: !secret vera_resource
    method: "GET"
    scan_interval: 20
    value_template: >-
      {% set mapper =  {                                                    
        '1' : 'Home',
        '2' : 'Away',                 
        '3' : 'Night',
        '4' : 'Vacation' } %}                
      {{ mapper[value] }}            
  # Local System monitor
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: swap_use_percent
      - type: disk_use_percent
        arg: /
      - type: processor_use
      - type: load_1m
      - type: last_boot
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    value_template: "{{ value | multiply(0.001) | float | round(0) }}"
    unit_of_measurement: " °C"
#    value_template: "{{ (value | multiply(0.0018) + 32) | float | round(0) }} °F"
  - platform: filesize                                                                                                             
    file_paths:                                                                                                                    
      - !secret database_file
  - platform: uptime
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
#      - 'date_time'
#      - 'date_time_utc'
#      - 'date_time_iso'
#      - 'time_date'
#      - 'time_utc'
  - platform: snmp
    host: 192.168.37.162
    baseoid: 1.3.6.1.2.1.25.1.8.1
    name: raspi_den_tr_cpu_temperature
    scan_interval: 60
    value_template: "{{ value }}"
    unit_of_measurement: " °C"
  - platform: snmp
    host: 192.168.37.163
    baseoid: 1.3.6.1.2.1.25.1.8.1
    name: raspi_garage_tr_cpu_temperature
    scan_interval: 60
    value_template: "{{ value }}"
    unit_of_measurement: " °C"
  - platform: snmp
    name: erx_wan_in
    host: 192.168.37.254
    baseoid: 1.3.6.1.2.1.31.1.1.1.6.10
    community: public
    version: '2c'
    scan_interval: 10
  - platform: snmp
    name: erx_wan_out
    host: 192.168.37.254
    baseoid: 1.3.6.1.2.1.31.1.1.1.10.10
    community: public
    version: '2c'
    scan_interval: 10
  - platform: derivative
    name: erx_wan_in_derivative
    source: sensor.erx_wan_in
    unit_time: s
    unit: B
  - platform: derivative
    name: erx_wan_out_derivative
    source: sensor.erx_wan_out
    unit_time: s
    unit: B
  - platform: snmp
    host: 192.168.37.254
    version: 2c
    name: CenturyLink WAN Usage
    scan_interval: 23
    unit_of_measurement: 'MiB'
    baseoid: 1.3.6.1.4.1.8072.1.3.2.4.1.2.10.119.97.110.95.117.115.97.103.101.0.1
    accept_errors: true
    value_template: '{{value | float}}'
  - platform: statistics                                                   
    name: CenturyLink WAN Statistics
    entity_id: sensor.centurylink_wan_usage
    state_characteristic: change
    sampling_size: 28800
    max_age:
      hours: 24
  - platform: integration
    source: sensor.ups_watts
    name: UPS Energy
    unit_prefix: k
    unit_time: h
    round: 2

# Add the moon
  - platform: moon

bme280:
  - name: Machine Room
    monitored_conditions:
      - temperature
      - humidity
      - pressure

switch:
  - platform: command_line
    switches:
      tworoads_pi_hole:
        command_on: !secret tworoads_pihole_enable
        command_off: !secret tworoads_pihole_disable
        command_state: !secret tworoads_pihole_status
        value_template: "{{ value_json.status == 'enabled' }}"

utility_meter:
  daily_energy:
    source: sensor.house_energy_delivered
    cycle: daily
  monthly_energy:
    source: sensor.house_energy_delivered
    cycle: monthly

#iqvia:
#  zip_code: "98407"
  
weather:
# Darksky
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily
    scan_interval:
      minutes: 15
# NWS weather
#  - platform: nws
#    mode: daynight # default daynight
#    station: KTIW
#    api_key: srp@tworoads.net

# Text to speech
#tts:
#  - platform: google_translate

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/bignumber-card/bignumber-card.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js
      type: module
    - url: /hacsfiles/flex-horseshoe-card/flex-horseshoe-card.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js                                                          
      type: module                                                                                                                 
    - url: /hacsfiles/bar-card/bar-card.js                                                                                         
      type: module                                                                                                                 
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/entity-attributes-card/entity-attributes-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/home-assistant-sun-card/home-assistant-sun-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/compass-card/compass-card.js
      type: module

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

history: !include history.yaml
recorder: !include recorder.yaml
automation: !include automations.yaml
automation split: !include_dir_list automations
#binary_sensor: !include binary_sensors.yaml
#group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
template: !include templates.yaml
rest_command: !include rest.yaml
zone: !include zones.yaml
