custom_header:
  compact_mode: true
title: Tworoads
views:
  - !include /config/lovelace/tworoads/views/home.yaml
  - !include /config/lovelace/tworoads/views/weather.yaml
  - !include /config/lovelace/tworoads/views/net_ops.yaml
  - !include /config/lovelace/tworoads/views/tracking.yaml
  - !include /config/lovelace/tworoads/views/sensors.yaml
