alias: "A: Vacation Mode, after 16hrs"       
trigger:
  - platform: state
    entity_id: binary_sensor.both_away
    to: 'on'
    for:
      hours: 16
action:                                                                   
  - service: rest_command.hm_command
    data_template:                                                           
      mode: 4
  - service: !secret telegram_notify
    data_template:                                                             
      message: Enter Vaction mode, 16hrs inactive
