# On Vacation, put HVAC in away mode, and turn off lights
id: 'hometovacation'
alias: "HVAC and Lights, Switches to Vacation"
trigger:
  platform: state
  entity_id: sensor.vera_house_mode
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ trigger.from_state.state != "unavailable" }}'
    - condition: template
      value_template: '{{ trigger.to_state.state == "Vacation" }}'
    - condition: template
      value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
action:                                                                   
  - service: scene.turn_on
    target:
      entity_id: scene.vacation
  - service: climate.set_preset_mode
    target:
      entity_id: climate.main_floor
    data:
      preset_mode: "away"
  - service: !secret telegram_notify
    data_template:
      message: "A: HVAC and Lights to Vacation"
