id: 'sideyardsnapshot'
alias: 'N: Side Yard Snapshot'
mode: single # Only run once at a time  
max_exceeded: silent # Hide warnings when triggered while in delay.
trigger:
  platform: state
  entity_id: binary_sensor.tr_side_yard_motion
  to: 'on'
action:
#  - delay: '2'
#  - service: unifiprotect.save_thumbnail_image
  - service: camera.snapshot
    data:
      entity_id: camera.tr_side_yard_high
      filename: "/config/www/snapshots/tr_side_yard.png"
#  - service: !secret telegram_notify
#    data_template:
#      message: "Side Yard Motion"
#  - service: !secret telegram_notify
#    data:
#      title: ''
#      message: ''
#      data:
#        photo:
#        - file: "/config/www/snapshots/tr_side_yard.png"
#          caption: "Side Yard {{now().strftime('%H:%M %d-%m-%Y')}}"
