# Daily weather report
id: 'dailyweatherreport'
alias: 'N: Daily Weather Report'
trigger:
  platform: time
  at: '05:30:00'
action:
  service: automation.trigger
  entity_id: automation.weather_report
