sensor:
  - platform: template
    sensors:
      solar_elevation:
        friendly_name: "Sonnenstand"
        unit_of_measurement: '°'
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      solar_azimuth:
        friendly_name: "Azimut"
        unit_of_measurement: '°'
        value_template: "{{ state_attr('sun.sun', 'azimuth') }}"
