# Help message      
id: 'helpmessage'
alias: "C: Telegram Command Help"
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/help'
action:
  service: !secret telegram_notify
  data:
    title: "Commands:"
    message: |
      /mode [home|away|night|vacation] - change Home mode.
      /ping - request a test response.
      /reboot - reboot the HA host.
      /restart - restart the HA container.
      /info - get basic house info
      /thermostat [home|away|status] - change thermostat mode.
      /weather - request a weather report.
      /usage - 24hr rolling internet usage.
