# Test message                           
id: 'testiosmessage'                                                                                                               
alias: "C: iOS Test Notification"                                                                              
trigger:                                                                                      
  platform: event                                                                           
  event_type: telegram_command                                                                      
  event_data:                                                                                  
    command: '/check'                                                       
action:                                                  
  service: notify.mobile_app_scott_s_iphone              
  data:                                              
    message: "iOS notified!"
