id: "sunset"                           
alias: 'N: Sunset Message'                                                                                                            
initial_state: 'off'
trigger:                                                                                               
  platform: sun                                                                               
  event: sunset                                                                             
action:                                                                                             
  service: notify.mobile_app_scott_s_iphone                                                    
  data:                                                                     
    message: 'Sunset {{ now().strftime("%H:%M") }}'      
