# Put HVAC in away mode
id: 'sethvacaway'
alias: "A: Set HVAC Away on Entering Vacation"
trigger:
  platform: state
  entity_id: sensor.vera_house_mode
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ trigger.from_state.state != "unavailable" }}'
    - condition: template
      value_template: '{{ trigger.to_state.state == "Vacation" }}'
    - condition: template
      value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
action:                                                                   
  - service: climate.set_preset_mode
    data_template:
      entity_id: climate.main_floor
      preset_mode: away
  - service: !secret telegram_notify
    data_template:
      message: "A: Thermostat set Away"
