# Century Link Usage Report
id: 'wanusagereport'
alias: "N: WAN Usage Report"
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/usage'
action:
  - service: !secret telegram_notify
    data_template:
      message: | 
       24 Hour WAN Usage: {{ state_attr('sensor.centurylink_wan_statistics', 'change') | round(0) }} MiB
       Monthy LTE Usage: {{ states('sensor.centurylink_wan_usage_gb') | round(0) }} GiB
